### ISSUE TITLE
Previous release 0.4.0, latest release 0.3.90 

### ISSUE THREAD

**Issue by fabaff** [flz/iaqualink-py#10]
The previous release was [0.4.0](https://github.com/flz/iaqualink-py/releases/tag/v0.4.0). Yesterday [0.3.90](https://github.com/flz/iaqualink-py/releases/tag/v0.3.90) was released.

It looks like that both branches (`master` and `0.3.x` ) contains the API endpoint URLs. Could you please release 0.4.1 if the update URLs are needed for 0.4.x too? Otherwise it would require that distributions patch their packages till 0.4.1 is released.

Thanks

**Comment by flz** [comment]
Yup, I was crunched for time and optimized for home-assistant to be fixed ASAP. I'll roll a new 0.4.1 today.

**Comment by flz** [comment]
Apologies for the delay. I just released 0.4.1. Thanks!
