### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by riverscuomo** [flz/iaqualink-py#11]
Thanks for the cool package. I've using it for a couple of years with a python script. It recently stopped working. I'm getting this error.

`C:\Program Files\Python38\lib\site-packages\iaqualink\client.py", line 110, in login`
   ` raise AqualinkLoginException(f"Login failed: {r.status} {r.reason}")`
`iaqualink.client.AqualinkLoginException: Login failed: 403 Forbidden`

My login credentials work still work fine on the website.

I'm currently using iaqualink==0.2.9 but I tried upgrading the most recent version and I still got the same error.

Any ideas?

**Comment by flz** [comment]
Hey, can you try iaqualink=0.3.90 to see if this fixes your issue?

I still need to create a new 0.4.x release that contains the latest fix.

**Comment by flz** [comment]
I just released iaqualink 0.4 which should work as well.

**Comment by riverscuomo** [comment]
Holy smokes it worked! Thank you. I'm using iaqualink=0.3.90. It looks like 0.4 would require a little bit of re-coding on my part.

**Comment by flz** [comment]
Yeah, I changed the API so I bump the minor version. Glad it fixed your issue in any case!
