### ISSUE TITLE
Devices showing offline

### ISSUE THREAD

**Issue by reitermarkus** [flz/iaqualink-py#13]
Hi,

for me all devices are showing as offline. They even show as offline on `iaqualink.zodiacpoolsystems.com`, so probably not an issue with this library.

I can however see all of them as online in the iOS app, so maybe there was another API change? Or is it just me?

**Comment by flz** [comment]
Don't seem to be having an issue here. What version of iaqualink-py are you using?

**Comment by reitermarkus** [comment]
I'm using version `0.4.1`.

I do get

```
exo is not a supported system type.
vr is not a supported system type.
```

Maybe those devices are using a different API? As you can see I can list them, but as I said, they show as offline, even though in the app they are showing as online.

Also tried using Charles Proxy and found the iOS app also uses these URLs:

- `https://prod.zodiac-io.com/devices/v1/<serial>/info`
- `https://prod.zodiac-io.com/devices/v1/<serial>/info`
- `https://prod.zodiac-io.com/devices/v2/<serial>/features`

They don't seem to give any interesting information, only very basic information.

The buttons in the app (Mode/ON/OFF, AUX 1, AUX 2) don't seem to send any HTTP requests.

**Comment by flz** [comment]
Ok, I was under the impression that the library worked and it stopped working.

I do not have access to either of those systems and it doesn't seem like the API is very similar to "iaqua" (Jandy) systems.

**Comment by reitermarkus** [comment]
I found the correct API here: https://community.home-assistant.io/t/jandy-iaqualink-pool-integration/105633/276
