### ISSUE TITLE
Issues with recent 0.4.X releases

### ISSUE THREAD

**Issue by schumra** [flz/iaqualink-py#17]
It looks like there is an issue with the 0.4.X release of iaqualink. Looking at the module contents, it looks like it's empty. The module was installed via pip/python3.9

Version 0.4.1, sane thing for 0.4.0
Python 3.9.10 (main, Feb  4 2022, 08:57:12) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import iaqualink as a
>>> dir(a) 
['__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'annotations']
>>> a.__version__
'0.4.1'

Version 0.3.90, which is working. 
>>> import iaqualink as a
>>> dir(a)
['AqualinkAuxToggle', 'AqualinkBinarySensor', 'AqualinkClient', 'AqualinkColorLight', 'AqualinkDevice', 'AqualinkDimmableLight', 'AqualinkHeater', 'AqualinkLight', 'AqualinkLightEffect', 'AqualinkLightToggle', 'AqualinkLightType', 'AqualinkLoginException', 'AqualinkPoolSystem', 'AqualinkPump', 'AqualinkSensor', 'AqualinkState', 'AqualinkSystem', 'AqualinkThermostat', 'AqualinkToggle', '__author__', '__builtins__', '__cached__', '__doc__', '__email__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', 'annotations', 'client', 'const', 'device', 'exception', 'system', 'typing']
>>> a.__version__
'0.3.90'

**Comment by flz** [comment]
That's expected, use the submodules instead (e.g. iaqualink.client).

**Comment by schumra** [comment]
Got it, thank you.
