### ISSUE TITLE
API Support for Aquapure

### ISSUE THREAD

**Issue by derekatkins** [flz/iaqualink-py#9]
Is there any API access to the AquaPure?  It is available in the iAqualink WebUI (if you click on the "status" icon).  I haven't seen any official API documentation; the Android App only has access to it "via the webUI".

It would be really nice to be able to see pool salt level as a sensor and be able to control the Pool and Spa generation, but I suspect the only way to do that is via the webUI?

**Comment by flz** [comment]
I don't have access to the equipment or documentation for an existing API so I'm not able to help at this time.

The alternative is to write a new library that uses scraping (similar to what this library looked like at the beginning). I assume Home Assistant support is the end game so support for this new library couldn't be integrated in hass itself but would have to be installed via HACS.
